import { execFile } from "child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "fs";
import { rm } from "fs/promises";
import { promisify } from "util";
import {
  CONFIG_DIR,
  WATCHERS_FILE,
  LAUNCH_AGENT_DIR,
  LAUNCH_AGENT_NAME,
  LAUNCH_AGENT_PLIST,
  ImageQualityPreset,
  IMAGE_QUALITY_SETTINGS,
  XATTR_KEY,
} from "./constants";

const run = promisify(execFile);

export interface WatchedFolder {
  path: string;
  mode: ImageQualityPreset;
  addedAt: string;
}

function ensureConfigDir(): void {
  if (!existsSync(CONFIG_DIR)) mkdirSync(CONFIG_DIR, { recursive: true });
}

export function loadWatchers(): WatchedFolder[] {
  ensureConfigDir();
  if (!existsSync(WATCHERS_FILE)) return [];
  try {
    return JSON.parse(readFileSync(WATCHERS_FILE, "utf-8"));
  } catch {
    return [];
  }
}

export function saveWatchers(watchers: WatchedFolder[]): void {
  ensureConfigDir();
  writeFileSync(WATCHERS_FILE, JSON.stringify(watchers, null, 2));
}

export async function addWatcher(
  path: string,
  mode: ImageQualityPreset,
): Promise<WatchedFolder[]> {
  const watchers = loadWatchers();
  if (watchers.some((w) => w.path === path)) return watchers;
  watchers.push({ path, mode, addedAt: new Date().toISOString() });
  saveWatchers(watchers);
  await updateLaunchAgent(watchers);
  return watchers;
}

export async function removeWatcher(path: string): Promise<WatchedFolder[]> {
  let watchers = loadWatchers();
  watchers = watchers.filter((w) => w.path !== path);
  saveWatchers(watchers);
  if (watchers.length === 0) {
    await uninstallLaunchAgent();
  } else {
    await updateLaunchAgent(watchers);
  }
  return watchers;
}

function getScriptPath(): string {
  return `${CONFIG_DIR}/watch-compress.sh`;
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function generatePlist(watchers: WatchedFolder[]): string {
  const watchPaths = watchers
    .map((w) => `      <string>${xmlEscape(w.path)}</string>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LAUNCH_AGENT_NAME}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${xmlEscape(getScriptPath())}</string>
    </array>
    <key>WatchPaths</key>
    <array>
${watchPaths}
    </array>
    <key>StandardOutPath</key>
    <string>${xmlEscape(CONFIG_DIR)}/watcher.log</string>
    <key>StandardErrorPath</key>
    <string>${xmlEscape(CONFIG_DIR)}/watcher-error.log</string>
    <key>ThrottleInterval</key>
    <integer>5</integer>
</dict>
</plist>`;
}

// Per-preset tool settings, from the same table the extension uses
function qualityCases(): string {
  return (
    Object.entries(IMAGE_QUALITY_SETTINGS) as [
      ImageQualityPreset,
      (typeof IMAGE_QUALITY_SETTINGS)[ImageQualityPreset],
    ][]
  )
    .map(([preset, q]) => {
      const lossless = preset === "lossless";
      const png = lossless ? "" : `${q.pngMin}-${q.pngMax}`;
      const jpeg = lossless ? "" : String(q.jpegMax);
      const webp = lossless
        ? "-lossless -z 9 -exact"
        : `-q ${q.webpQuality} -m 6`;
      const gif = q.gifLossy > 0 ? `--lossy=${q.gifLossy}` : "";
      return `        ${preset}) PNG_QUAL="${png}"; JPEG_MAX="${jpeg}"; WEBP_ARGS="${webp}"; GIF_LOSSY="${gif}" ;;`;
    })
    .join("\n");
}

function generateWatchScript(watchers: WatchedFolder[]): string {
  const folders = watchers.map((w) => `    ${shellQuote(w.path)}`).join("\n");
  const modes = watchers.map((w) => `    ${shellQuote(w.mode)}`).join("\n");

  return `#!/bin/bash
# Media Compressor — Image Watcher
# Triggered by launchd WatchPaths when a watched folder changes.
# Generated by the extension; the folder list is rewritten on every change.

set -uo pipefail

CONFIG_DIR="$HOME/.config/media-compressor"
LOCK_FILE="$CONFIG_DIR/watcher.lock"
STAMP_DIR="$CONFIG_DIR/watcher-stamps"
export XATTR_KEY="${XATTR_KEY}"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

FOLDERS=(
${folders}
)
MODES=(
${modes}
)

if [ -f "$LOCK_FILE" ]; then
    LOCK_PID=$(cat "$LOCK_FILE" 2>/dev/null || echo "")
    if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null; then
        exit 0
    fi
fi
echo $$ > "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

if ! command -v oxipng &>/dev/null; then
    echo "oxipng not found" >&2
    exit 1
fi
mkdir -p "$STAMP_DIR"

# Half the cores: pngquant is single-threaded, oxipng already uses several
JOBS=$(( $(/usr/sbin/sysctl -n hw.ncpu) / 2 ))
[ "$JOBS" -lt 1 ] && JOBS=1
[ "$JOBS" -gt 6 ] && JOBS=6

# Succeeds only if the original actually left its path
trash_file() {
    if [ -x /usr/bin/trash ]; then
        /usr/bin/trash "$1" 2>/dev/null && [ ! -e "$1" ] && return 0
    fi
    # Before macOS 15 there is no trash command; move it into the user's Trash
    # under a name nothing else is using, and never overwrite what's there
    local name dest
    name=$(basename "$1")
    dest="$HOME/.Trash/$name"
    while [ -e "$dest" ] || [ -L "$dest" ]; do
        dest="$HOME/.Trash/$(date +%s)-$$-$RANDOM-$name"
    done
    mv -n "$1" "$dest" 2>/dev/null
    [ ! -e "$1" ]
}

# Returns non-zero only when the file should be tried again on a later run
# (original couldn't be trashed, tool not installed). A file the tool can't
# handle is marked like one that didn't get smaller, so it isn't retried forever.
compress_one() {
    local IMG="$1"
    local MARKED
    MARKED=$(xattr -p "$XATTR_KEY" "$IMG" 2>/dev/null || true)
    [ "$MARKED" = "true" ] && return 0

    # A file that just appeared may still be copying in; wait for its size to settle
    local AGE=$(( $(date +%s) - $(stat -f%m "$IMG" 2>/dev/null || echo 0) ))
    if [ "$AGE" -lt 5 ]; then
        local PREV=-1 CUR TRIES=0
        CUR=$(stat -f%z "$IMG" 2>/dev/null || echo -1)
        while [ "$CUR" != "$PREV" ] && [ "$TRIES" -lt 30 ]; do
            sleep 1
            PREV=$CUR
            CUR=$(stat -f%z "$IMG" 2>/dev/null || echo -1)
            TRIES=$((TRIES + 1))
        done
    fi

    local ORIG_SIZE EXT WORK OUT
    ORIG_SIZE=$(stat -f%z "$IMG" 2>/dev/null) || return 0
    EXT=$(echo "\${IMG##*.}" | tr '[:upper:]' '[:lower:]')
    WORK=$(mktemp -d "\${TMPDIR:-/tmp}/mediacomp.XXXXXX") || return 1
    OUT="$WORK/out.$EXT"

    local MISSING=""
    case "$EXT" in
        png)
            local QUANTIZED=false
            if [ -n "$PNG_QUAL" ] && command -v pngquant &>/dev/null; then
                pngquant --quality="$PNG_QUAL" --speed 1 --strip --force --output "$OUT" "$IMG" 2>/dev/null && QUANTIZED=true
            fi
            [ "$QUANTIZED" = true ] || cp "$IMG" "$OUT"
            oxipng -o 4 --strip safe -q "$OUT" 2>/dev/null || true
            ;;
        jpg|jpeg)
            cp "$IMG" "$OUT"
            if command -v jpegoptim &>/dev/null; then
                jpegoptim -q --strip-all --all-progressive \${JPEG_MAX:+--max=$JPEG_MAX} "$OUT" >/dev/null 2>&1 || true
            fi
            ;;
        webp)
            if command -v cwebp &>/dev/null; then
                # A failed run (e.g. an animated WebP) leaves no usable output
                # shellcheck disable=SC2086
                cwebp -quiet -mt -metadata none $WEBP_ARGS "$IMG" -o "$OUT" 2>/dev/null || rm -f "$OUT"
            else
                MISSING=cwebp
            fi
            ;;
        gif)
            if command -v gifsicle &>/dev/null; then
                # shellcheck disable=SC2086
                gifsicle -O3 --no-comments --no-names $GIF_LOSSY -o "$OUT" "$IMG" 2>/dev/null || rm -f "$OUT"
            else
                MISSING=gifsicle
            fi
            ;;
    esac

    if [ -n "$MISSING" ]; then
        echo "$(date '+%F %T'): Skipped $(basename "$IMG"): $MISSING isn't installed" >&2
        rm -rf "$WORK"
        return 1
    fi

    local NEW_SIZE STATUS=0
    NEW_SIZE=$(stat -f%z "$OUT" 2>/dev/null || echo 0)
    if [ "$NEW_SIZE" -gt 0 ] && [ "$NEW_SIZE" -lt "$ORIG_SIZE" ]; then
        # Never replace an original that didn't make it to the Trash
        if trash_file "$IMG"; then
            mv "$OUT" "$IMG"
            xattr -w "$XATTR_KEY" true "$IMG" 2>/dev/null || true
            echo "$(date '+%F %T'): Compressed $(basename "$IMG"): $((ORIG_SIZE / 1024))KB -> $((NEW_SIZE / 1024))KB (-$(( (ORIG_SIZE - NEW_SIZE) * 100 / ORIG_SIZE ))%)"
        else
            echo "$(date '+%F %T'): Skipped $(basename "$IMG"): couldn't move the original to the Trash, will retry" >&2
            STATUS=1
        fi
    else
        # Not smaller, or the tool couldn't process it: leave it as is for good
        xattr -w "$XATTR_KEY" true "$IMG" 2>/dev/null || true
    fi
    rm -rf "$WORK"
    return $STATUS
}
export -f compress_one trash_file

for i in "\${!FOLDERS[@]}"; do
    FOLDER="\${FOLDERS[$i]}"
    [ -d "$FOLDER" ] || continue

    case "\${MODES[$i]}" in
${qualityCases()}
        *) PNG_QUAL="85-100"; JPEG_MAX="90"; WEBP_ARGS="-q 90 -m 6"; GIF_LOSSY="--lossy=20" ;;
    esac
    export PNG_QUAL JPEG_MAX WEBP_ARGS GIF_LOSSY

    # Only look at files that changed since the last pass over this folder,
    # repeating until a pass finds nothing new (files can land mid-run)
    STAMP="$STAMP_DIR/$(/sbin/md5 -q -s "$FOLDER")"
    while true; do
        NEWER=()
        [ -f "$STAMP" ] && NEWER=(-cnewer "$STAMP")
        touch "$STAMP.next"
        OUTPUT=$(find "$FOLDER" -maxdepth 1 -type f \\( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' -o -iname '*.gif' \\) \${NEWER[@]+"\${NEWER[@]}"} -print0 \\
            | xargs -0 -n 1 -P "$JOBS" "$BASH" -c 'compress_one "$1"' _)
        PASS_STATUS=$?
        [ -n "$OUTPUT" ] && echo "$OUTPUT"
        if [ "$PASS_STATUS" -ne 0 ]; then
            # Some file needs another try: keep the old stamp so the next run
            # looks at it again, and stop here instead of spinning on it
            rm -f "$STAMP.next"
            break
        fi
        mv "$STAMP.next" "$STAMP"
        echo "$OUTPUT" | grep -q ': Compressed ' || break
    done
done
`;
}

export function installWatchScript(watchers: WatchedFolder[] = loadWatchers()) {
  ensureConfigDir();
  // Write a new file and swap it in: bash reads a script as it runs, so
  // rewriting it in place could hand a running watcher half of each version
  const scriptPath = getScriptPath();
  const tempPath = `${scriptPath}.${process.pid}.tmp`;
  writeFileSync(tempPath, generateWatchScript(watchers), { mode: 0o755 });
  renameSync(tempPath, scriptPath);
}

/**
 * Rewrites the watch script if it's out of date, e.g. after an extension
 * update. launchd runs it by path, so no reload is needed.
 */
export function syncWatchScript(): boolean {
  const watchers = loadWatchers();
  if (watchers.length === 0) return false;
  const scriptPath = getScriptPath();
  if (
    existsSync(scriptPath) &&
    readFileSync(scriptPath, "utf-8") === generateWatchScript(watchers)
  ) {
    return false;
  }
  installWatchScript(watchers);
  return true;
}

async function updateLaunchAgent(watchers: WatchedFolder[]): Promise<void> {
  if (watchers.length === 0) {
    await uninstallLaunchAgent();
    return;
  }

  installWatchScript(watchers);

  try {
    await run("/bin/launchctl", ["unload", LAUNCH_AGENT_PLIST]);
  } catch {
    // might not exist yet
  }

  if (!existsSync(LAUNCH_AGENT_DIR))
    mkdirSync(LAUNCH_AGENT_DIR, { recursive: true });
  writeFileSync(LAUNCH_AGENT_PLIST, generatePlist(watchers));
  await run("/bin/launchctl", ["load", LAUNCH_AGENT_PLIST]);
}

async function uninstallLaunchAgent(): Promise<void> {
  try {
    await run("/bin/launchctl", ["unload", LAUNCH_AGENT_PLIST]);
  } catch {
    /* */
  }
  await rm(LAUNCH_AGENT_PLIST, { force: true });
}

export async function isWatcherRunning(): Promise<boolean> {
  try {
    await run("/bin/launchctl", ["list", LAUNCH_AGENT_NAME]);
    return true;
  } catch {
    return false;
  }
}
